### ISSUE TITLE
Some columns can only be viewed in ascending order

### ISSUE THREAD

**Issue by adamhl8** [hssm/advanced-browser#102]
I haven't tested all of the columns but the following can only be be viewed in ascending order:

- Percent Correct
- Time (Average)
- Time (Total)

Clicking the column to toggle between ascending and descending on these columns does nothing and they just stay in ascending order.

**Comment by hssm** [comment]
Thanks for alerting me to the issue. A change in Anki's internals broke the sorting behavior so none of the "advanced" columns were sorting, and I haven't been keeping up with Anki's development so I wasn't aware that browser searching had changed.

I've released a new version with fixes for these, and for safety reasons (because I can't test every version) I have made it available only for Anki 2.1.35 and above.
