### ISSUE TITLE
Version at AnkiWeb does not work on Anki 2.1.0 Beta 23

### ISSUE THREAD

**Issue by aleksejrs** [hssm/advanced-browser#31]
```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Advanced Browser':
Traceback (most recent call last):
  File "aqt/addons.py", line 57, in loadAddons
  File "/home/fc/.local/share/Anki2/addons21/874215009/__init__.py", line 6, in <module>
    from core import AdvancedBrowser
ModuleNotFoundError: No module named 'core'
```

**Comment by hssm** [comment]
Thanks for letting me know. I've uploaded a new version to AnkiWeb that should hopefully resolve the issue. Please update it and give it a try.

**Comment by aleksejrs** [comment]
It doesn't work. The master branch works though. Maybe the problem is in `__init__.py`.

```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Advanced Browser':
Traceback (most recent call last):
  File "aqt/addons.py", line 57, in loadAddons
  File "/home/fc/.local/share/Anki2/addons21/874215009/__init__.py", line 6, in <module>
    import advancedbrowser
ModuleNotFoundError: No module named 'advancedbrowser'
```

**Comment by hssm** [comment]
I hadn't pushed my changes to github yet. The version in master was what the first version you tried was *supposed* to be, but it's almost like AnkiWeb rolled back the latest release I made since it contained a fix for this very issue from https://github.com/hssm/advanced-browser/issues/29.

Anyway, I've pushed another one that reverses those changes with a few tweaks. I've tested it myself on a clean build of the binary release so it should be good.
