### ISSUE TITLE
Column alignment

### ISSUE THREAD

**Issue by solidpearl** [hssm/advanced-browser#8]
Hi, I would like to have some columns left aligned. Is there a way to modify the script accordingly?

**Comment by kiuuik** [comment]
I'd like to have this feature, too. I think many people would benefit from such a feature because many people use Anki to learn much more than vocabulary. Even if you adhere to the minimum information principle some cards need to be quite long.

Over the years I have started to use Anki as some form of knowledge database. I do remember that I have put something inside, but I don't know the exact answer. So I regularly look in the browser, e.g. when I need some combination of cli commands. Then left alignment would be much more clear. At the moment in Advanced Browser centered cells in the table in the upper half of the browser are not really helpful.

I understand if you don't have the motivation to do this. I just tried to illustrate that left alignment is much more than a mere visual tweak. Anyway thanks for your great work.

**Comment by kiuuik** [comment]
@hssm : Can I increase your motivation sufficiently by offering 30€ or 30 USD for this feature as a prepayment via paypal?

**Comment by hssm** [comment]
How do you envision this feature to work, from a user interface perspective?

Looking into this a little more closely, it seems that Anki chooses to [explicitly left-align](https://github.com/dae/anki/blob/master/aqt/browser.py#L89) some of its internal columns (the non-numeric ones). Given that, it might make the most sense to left-align any column handled by this add-on as well.

I don't have any problems with doing that, and it would avoid creating a configurable element for the columns, but then some people might prefer to have the columns center aligned for whatever reason.

**Comment by thoral** [comment]
I think the most important is to left-align the text columns. If the others columns will be not centered anymore - well, I could live with this.

At the moment I have only two text columns centered: the field columns (front, back). The other ones (question, answer) are not centered anymore (Anki 2.0.44) like before.

Thanks for taking time regarding this issue!

**Comment by kiuuik** [comment]
My idea is that the table of cards in Advanced Browser looks exactly like the regular browser. I was motivated by the position of longer texts on fields like front and back. I didn't even think of numeric columns.

Maybe two pictures show better why I want left-alignment. Here is an example of some old cards I made shown in Advanced Browser:
![ankiadvancedbrowsercentered](https://cloud.githubusercontent.com/assets/19992955/23898896/414c5302-08b3-11e7-9abf-721a3f1a3322.png)
Because the text is centered I cannot quickly browse them. My focus has to jump around horizontally. On longer cards I see the middle of the text which is not as understandable as the first part of a question. 

Here are the same cards in the regular browser:
![ankibrowserlinksbundig](https://cloud.githubusercontent.com/assets/19992955/23898953/787d952a-08b3-11e7-97d8-48c8a433aa46.png)

You mention the problem that some people might prefer the current implementation that centers text. Admittedly you never know what people will ask. But I think most people will have used the default browser for some time before they come to addons and advanced browser. So they will be accustomed to left-aligned text. I also did a quick search on tenderapp and /r/anki. I didn't find anything useful for combinations of "centered/center align browser". So I think people haven't asked for this feature for the regular browser. And I don't think that there is a silent majority of advanced-browser users who prefer a centered view. Apart from this I don't see any benefits of centered text in the browser.

**Comment by hssm** [comment]
I've just put up a new version on AnkiWeb that uses left-alignment for any column maintained by the add-on. Please test it and let me know how you go.

As a bonus, fields marked as RTL are now right-aligned: 
![rtl](https://cloud.githubusercontent.com/assets/789082/23988264/8a24b8ce-0a81-11e7-8fcb-5809a81ee3b0.png)

So we are now a little bit more advanced than the stock browser in this regard.

**Comment by thoral** [comment]
Great, thank you!

**Comment by kiuuik** [comment]
It looks much better now. Everything seems to work. Thanks a lot.

And now the alignment can be easily adjusted by changing two words in line 102 ("align = Qt.AlignVCenter | Qt.AlignLeft"). So if for whatever reason someone doesn't like your new default left-alignment they can easily revert it by adjusting "AlignVCenter" and/or "AlignLeft" (I found other possible values [here](http://doc.qt.io/qt-4.8/qt.html#AlignmentFlag-enum)).

Where should I transfer the money?

**Comment by hssm** [comment]
You can use this address with paypal: `ntsp.gm@gmail.com`. Thanks!
